networks:
  dev:

volumes:
  app-data:

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - app-data:/just_data
    depends_on:
      - frontend
      - backend
    networks:
      - dev

  backend:
    build:
      context: ./backend
    networks:
      - dev
    volumes:
      - app-data:/just_data

  frontend:
    build: 
      context: ./frontend
    networks:
      - dev
    volumes:
      - app-data:/just_data